import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import styles from '@/styles';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`${styles.boxWidth}`}>{children}</div>
      </body>
    </html>
  );
}
