import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import styles from '@/styles';

const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  display: 'swap',
  subsets: ['latin', 'latin-ext'],
  preload: true,
  fallback: ['Arial', 'sans-serif'],
  adjustFontFallback: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className={`${styles.boxWidth}`}>{children}</div>
      </body>
    </html>
  );
}
