import type { Metadata } from 'next';
import { Oswald } from 'next/font/google';
import './globals.css';
import styles from '@/styles';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const oswald = Oswald({
  weight: ['400', '700'], // Include regular and bold weights
  subsets: ['latin', 'latin-ext'], // Include Latin and extended Latin subsets
  display: 'swap', // Use fallback fonts while loading
  variable: '--font-oswald', // Generate a CSS variable for the font
  adjustFontFallback: true, // Adjust fallback fonts to prevent layout shifts
  preload: true, // Preload the font in the document head
  fallback: ['Arial', 'sans-serif'], // Fallback fonts
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`${styles.boxWidth} ${oswald.variable}`}>
          {children}
        </div>
      </body>
    </html>
  );
}
